const URL="wss://tts.bhashini.ai/stt/stream";const RATE=16000;
export type VoiceStatus="idle"|"starting"|"streaming";
export class BhashiniStreamingClient{
 status:VoiceStatus="idle"; private stream?:MediaStream;private socket?:WebSocket;private ctx?:AudioContext;private source?:MediaStreamAudioSourceNode;private node?:AudioWorkletNode;private gain?:GainNode;
 constructor(private apiKey:string,private language:string,private handlers:{onInterim:(t:string)=>void;onFinal:(t:string)=>void;onStatus:(s:VoiceStatus)=>void;onError:(e:Error)=>void}){}
 async start(){if(this.status!=="idle")return;if(!this.apiKey)throw new Error("BHASHINI API key is not configured.");if(!/^[A-Za-z0-9]{32}$/.test(this.apiKey))throw new Error("BHASHINI key must be a valid 32-character API key.");this.setStatus("starting");try{this.stream=await navigator.mediaDevices.getUserMedia({audio:true});this.ctx=new AudioContext({sampleRate:RATE});if(this.ctx.state==="suspended")await this.ctx.resume();await this.ctx.audioWorklet.addModule("/pcm-capture.worklet.js");this.source=this.ctx.createMediaStreamSource(this.stream);this.node=new AudioWorkletNode(this.ctx,"pcm-capture-worklet",{processorOptions:{chunkSize:1024}});this.gain=this.ctx.createGain();this.gain.gain.value=0;this.source.connect(this.node);this.node.connect(this.gain);this.gain.connect(this.ctx.destination);this.node.port.onmessage=e=>this.handleAudio(e.data);this.socket=new WebSocket(URL,[`apikey.${this.apiKey}`]);this.socket.binaryType="arraybuffer";this.socket.onopen=()=>{this.socket?.send(JSON.stringify({event:"start",language:this.language,useVad:true,inputEncoding:{encoding:"linear16",samplingRate:RATE,bitsPerSample:16,numChannels:1,isSigned:true,isBigEndian:false},interimIntervalMs:200}));this.setStatus("streaming")};this.socket.onmessage=e=>this.handleMessage(e.data);this.socket.onerror=()=>this.handlers.onError(new Error("BHASHINI streaming connection error."));this.socket.onclose=()=>{this.cleanup();this.setStatus("idle")}}catch(e){this.cleanup();this.setStatus("idle");throw e}}
 async stop(){if(this.status==="idle")return;try{this.node?.port.postMessage({type:"flush"});if(this.socket?.readyState===WebSocket.OPEN)this.socket.send(JSON.stringify({event:"stop"}));setTimeout(()=>this.socket?.close(),120)}finally{this.cleanup();this.setStatus("idle")}}
 private handleMessage(raw:string){try{const p=JSON.parse(raw);if(typeof p?.transcript!=="string")return;p.isFinal?this.handlers.onFinal(p.transcript):this.handlers.onInterim(p.transcript)}catch{}}
 private handleAudio(data:any){if(data?.type!=="pcm-chunk"||!this.socket||this.socket.readyState!==WebSocket.OPEN)return;const f=data.chunk instanceof Float32Array?data.chunk:new Float32Array(data.chunk);const pcm=this.to16k(f,this.ctx?.sampleRate||RATE);this.socket.send(this.toPcm16(pcm))}
 private to16k(input:Float32Array,inputRate:number){if(inputRate===RATE)return input;const ratio=inputRate/RATE,out=new Float32Array(Math.max(1,Math.round(input.length/ratio)));for(let i=0;i<out.length;i++){const start=Math.floor(i*ratio),end=Math.min(input.length,Math.floor((i+1)*ratio));let sum=0;for(let j=start;j<Math.max(end,start+1);j++)sum+=input[j]||0;out[i]=sum/Math.max(1,end-start)}return out}
 private toPcm16(input:Float32Array){const b=new ArrayBuffer(input.length*2),v=new DataView(b);input.forEach((x,i)=>v.setInt16(i*2,Math.max(-1,Math.min(1,x))<0?Math.max(-1,Math.min(1,x))*0x8000:Math.max(-1,Math.min(1,x))*0x7fff,true));return b}
 private setStatus(s:VoiceStatus){this.status=s;this.handlers.onStatus(s)}
 private cleanup(){try{this.node?.disconnect();this.source?.disconnect();this.gain?.disconnect()}catch{}this.stream?.getTracks().forEach(t=>t.stop());this.ctx?.close().catch(()=>{});this.node=undefined;this.source=undefined;this.gain=undefined;this.stream=undefined;this.ctx=undefined;this.socket=undefined}
}