import React,{useRef,useState,useEffect} from "react";
import {createRoot} from "react-dom/client"; import "./styles.css"; import {t} from "./i18n.js";
type Page="home"|"intake"|"profile"|"records"|"abha"|"login";
const API=import.meta.env.VITE_PRISM_API_URL||"http://localhost:8000";
const LANGUAGES:[string,string][]=[["en-IN","English"],["hi-IN","हिन्दी"],["ta-IN","தமிழ்"]];
function optionValueLabel(o:any){return typeof o==="string"?{value:o,label:o}:{value:o.value,label:o.label}}
function App(){
 const [page,setPage]=useState<Page>("home"),[session,setSession]=useState<any>(null),[text,setText]=useState(""),[loading,setLoading]=useState(false),[language,setLanguage]=useState("en-IN"),[profile,setProfile]=useState<any>({conditions:"",medicines:"",allergies:""}),[record,setRecord]=useState<any>(null),[recordStatus,setRecordStatus]=useState(""),[error,setError]=useState(""),[patient,setPatient]=useState<any>(null),[mobile,setMobile]=useState(""),[otp,setOtp]=useState(""),[tx,setTx]=useState(""),[otpHint,setOtpHint]=useState(""),[afterLogin,setAfterLogin]=useState<Page>("abha"),[savedIssue,setSavedIssue]=useState(false);
 const [intakeUpload,setIntakeUpload]=useState<any>(null);
 const [confirmedEvidence,setConfirmedEvidence]=useState<Set<string>>(new Set());
 const [rejectedEvidence,setRejectedEvidence]=useState<Set<string>>(new Set());
 const [recording,setRecording]=useState(false);
 const [transcribing,setTranscribing]=useState(false);
 const inputRef=useRef<HTMLInputElement>(null);
 const intakeFileRef=useRef<HTMLInputElement>(null);
 const mediaRecorderRef=useRef<MediaRecorder|null>(null);
 const audioChunksRef=useRef<Blob[]>([]);
 const recordingStartRef=useRef(0);
 const clearStaleSession=()=>{localStorage.removeItem("setu_patient");setPatient(null);setProfile({conditions:"",medicines:"",allergies:""});setSession(null);setPage("home")};
 const request=async(url:string,init?:RequestInit)=>{const r=await fetch(API+url,init);const d=await r.json().catch(()=>null);if(!r.ok){const code=d?.error||d?.message||String(r.status);if(code==="patient_not_found"){clearStaleSession();throw new Error("Your saved session is no longer on this server (it may have restarted) — reconnect to continue.")}throw new Error(code)}return d};
 const persist=(p:any)=>{setPatient(p);setProfile(p.profile||{});localStorage.setItem("setu_patient",JSON.stringify(p))};
 const refreshPatient=async(id?:string)=>{const patientId=id||patient?.patientId;if(!patientId)return null;const p=await request("/v1/abha/patients/"+patientId);persist(p);return p};
 useEffect(()=>{const raw=localStorage.getItem("setu_patient");if(!raw)return;try{const cached=JSON.parse(raw);setPatient(cached);setProfile(cached.profile||{});request("/v1/abha/patients/"+cached.patientId).then(p=>persist(p)).catch(()=>{});}catch{localStorage.removeItem("setu_patient")}},[]);
 const requirePatient=(target:Page)=>{if(patient){setPage(target);refreshPatient().catch(()=>{});return true}setAfterLogin(target);setPage("login");return false};
 const requestOtp=async()=>{setLoading(true);setError("");try{const r=await request("/v1/abha/otp/request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mobile})});setTx(r.transaction_id);setOtpHint(r.demo_otp||"");}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const verifyOtp=async()=>{setLoading(true);setError("");try{const r=await request("/v1/abha/otp/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transaction_id:tx,otp})});persist(r.patient);setTx("");setOtp("");if(afterLogin==="intake"){setSavedIssue(false);setIntakeUpload(null);const s=await request("/v1/intake/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language,entry_point:"current_health_issue",patient_id:r.patient.patientId})});setSession(s)}setPage(afterLogin);}catch(e:any){setError("Verification failed: "+e.message)}finally{setLoading(false)}};
 const start=async()=>{if(!patient){setAfterLogin("intake");setPage("login");return}setLoading(true);setError("");setSavedIssue(false);setIntakeUpload(null);try{const s=await request("/v1/intake/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language,entry_point:"current_health_issue",patient_id:patient.patientId})});setSession(s);setPage("intake")}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const completeIssue=async()=>{if(!session||!patient||savedIssue)return;setLoading(true);setError("");try{const summary=await request("/v1/intake/sessions/"+session.id+"/summary");const updated=await request("/v1/abha/patients/"+patient.patientId+"/issues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:summary.chief_complaint||"Current health issue",summary,session_id:session.id,language,voice_transcripts:summary.turns||[]})});persist(updated);setSavedIssue(true);setPage("abha")}catch(e:any){setError("Could not save the health issue: "+e.message)}finally{setLoading(false)}};
 const send=async(value:string,mode="text")=>{if(!session||!value.trim())return;setLoading(true);setError("");try{const next=await request("/v1/intake/sessions/"+session.id+"/responses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value,input_mode:mode})});setSession(next);setText("")}catch(e:any){setError("Response failed: "+e.message)}finally{setLoading(false)}};
 const startRecording=async()=>{setError("");try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const mr=new MediaRecorder(stream);audioChunksRef.current=[];recordingStartRef.current=Date.now();mr.ondataavailable=(e:BlobEvent)=>{if(e.data.size>0)audioChunksRef.current.push(e.data)};mr.onstop=async()=>{stream.getTracks().forEach(tr=>tr.stop());const durationMs=Date.now()-recordingStartRef.current;if(durationMs<600){setError("Recording was too short to transcribe — hold the button a little longer and speak, then try again.");return}const blob=new Blob(audioChunksRef.current,{type:mr.mimeType||"audio/webm"});setTranscribing(true);try{const form=new FormData();form.append("file",blob,"speech.webm");const result=await request("/v1/asr/transcribe?language="+encodeURIComponent(language),{method:"POST",body:form});const transcript=(result.text||"").trim();if(!transcript){setError("Could not make out any speech in that recording — please try again, speaking clearly.");return}setText(prev=>prev?prev+" "+transcript:transcript)}catch(e:any){setError("Voice transcription failed: "+e.message)}finally{setTranscribing(false)}};mediaRecorderRef.current=mr;mr.start();setRecording(true)}catch(e:any){setError("Microphone access failed: "+e.message)}};
 const stopRecording=()=>{mediaRecorderRef.current?.stop();setRecording(false)};
 const speak=()=>{recording?stopRecording():startRecording()};
 const speakQuestion=()=>{const synth=(window as any).speechSynthesis;const text=session?.nextAction?.patient_text;if(!synth||!text)return;try{synth.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=language;synth.speak(u)}catch{}};
 const saveProfile=async()=>{if(!patient)return;setLoading(true);setError("");try{const p=await request("/v1/abha/patients/"+patient.patientId+"/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile})});persist(p);setRecordStatus("Health profile saved to your shared patient record.")}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const upload=async(file:File)=>{if(!patient){setAfterLogin("records");setPage("login");return}setLoading(true);setError("");setRecordStatus("Uploading source document…");try{const form=new FormData();form.append("file",file);const up=await request("/v1/resources/upload?patient_id="+encodeURIComponent(patient.patientId),{method:"POST",body:form});setRecord(up.resource);setRecordStatus("Running multilingual OCR and evidence extraction…");const result=await request("/v1/resources/"+up.resource.resourceId+"/process",{method:"POST"});const saved={...up.resource,processing:result};setRecord(saved);const updated=await request("/v1/abha/patients/"+patient.patientId+"/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource_id:up.resource.resourceId,title:file.name,media_type:file.type,processing_status:result.status,evidence_count:result.evidence?.length||0})});persist(updated);setRecordStatus(result.status==="completed"?"OCR completed and linked to your shared patient record.":"Processing finished with an error.")}catch(e:any){setError("Document processing failed: "+e.message);setRecordStatus("")}finally{setLoading(false)}};
 const uploadDuringIntake=async(file:File)=>{if(!patient||!session)return;setLoading(true);setError("");setIntakeUpload({status:"uploading",filename:file.name});try{const form=new FormData();form.append("file",file);const up=await request("/v1/resources/upload?patient_id="+encodeURIComponent(patient.patientId),{method:"POST",body:form});setIntakeUpload({status:"processing",filename:file.name});const result=await request("/v1/resources/"+up.resource.resourceId+"/process",{method:"POST"});const evidenceIds=(result.evidence||[]).map((e:any)=>e.id);await request("/v1/intake/sessions/"+session.id+"/evidence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource_id:up.resource.resourceId,evidence_ids:evidenceIds,original_filename:file.name})});await request("/v1/abha/patients/"+patient.patientId+"/records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource_id:up.resource.resourceId,title:file.name,media_type:file.type,processing_status:result.status,evidence_count:evidenceIds.length})}).then(persist).catch(()=>{});setIntakeUpload({status:"done",filename:file.name,evidenceCount:evidenceIds.length})}catch(e:any){setError("Document processing failed: "+e.message);setIntakeUpload(null)}finally{setLoading(false)}};
 const confirmEvidence=async(evidenceId:string)=>{if(!patient)return;try{await request("/v1/patients/"+patient.patientId+"/evidence/"+evidenceId+"/confirm",{method:"POST"});setConfirmedEvidence(prev=>new Set(prev).add(evidenceId))}catch(e:any){setError(e.message)}};
 const rejectEvidence=async(evidenceId:string)=>{if(!patient)return;try{await request("/v1/patients/"+patient.patientId+"/evidence/"+evidenceId,{method:"DELETE"});setRejectedEvidence(prev=>new Set(prev).add(evidenceId))}catch(e:any){setError(e.message)}};
 const nav=(p:Page)=>{if(p==="profile"||p==="records"||p==="abha")requirePatient(p);else setPage(p)};
 const complete=session?.nextAction?.type==="COMPLETE_SECTION"||session?.state==="history";
 const selectingCondition=session?.nextAction?.type==="SELECT_CONDITION";
 return <div className="app"><header><div className="brand">SETU <span>PRISM</span></div><nav>{([["home",t("nav_home",language)],["profile",t("nav_my_health",language)],["records",t("nav_records",language)],["abha",t("nav_abha",language)]] as [Page,string][]).map(([p,label])=><button key={p} onClick={()=>nav(p)} className={page===p?"active":""}>{label}</button>)}<select value={language} onChange={e=>setLanguage(e.target.value)}>{LANGUAGES.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select>{patient&&<button onClick={()=>{localStorage.removeItem("setu_patient");setPatient(null);setProfile({conditions:"",medicines:"",allergies:""});setPage("home")}}>{t("nav_disconnect",language)}</button>}</nav></header>
 {error&&<div className="banner error">{error}<button onClick={()=>setError("")}>×</button></div>}
 {page==="home"&&<main className="hero"><p className="eyebrow">MULTILINGUAL DIGITAL HEALTH · HACKATHON DEMO</p><h1>One place for your health journey.<br/><span>Start with what matters now.</span></h1><p className="sub">SETU connects patient intake, voice interaction, medical records and consented health context into one patient-owned journey.</p>{!patient&&<div className="notice">Start by connecting your mobile number through OTP consent. Your patient-side workspace opens after verification.</div>}<div className="grid"><button className="card primary" onClick={start}><b>🩺 I have a health concern</b><span>Describe what is troubling you. PRISM will ask a few relevant questions in your language.</span><small>Start case-taking →</small></button><button className="card" onClick={()=>nav("records")}><b>📄 Add previous medical records</b><span>Upload reports and prescriptions. Originals remain linked to extracted information.</span><small>Open records →</small></button><button className="card" onClick={()=>nav("profile")}><b>❤️ Build my health profile</b><span>Progressively build conditions, medicines and allergies.</span><small>Explore profile →</small></button><button className="card" onClick={()=>nav("abha")}><b>🏥 Connect ABHA</b><span>{patient?"Open your patient-side health workspace.":"Verify mobile identity and establish consent."}</span><small>{patient?"Open workspace →":"Connect →"}</small></button></div></main>}
 {page==="login"&&<main className="intake"><p className="eyebrow">PATIENT IDENTITY & CONSENT</p><h2>{tx?"Verify your consent":"Connect your patient identity"}</h2><p className="muted">Demo flow: mobile OTP establishes a patient session and opens the patient-side ABHA workspace. Production ABDM integration remains credential-gated.</p>{!tx?<><input className="textInput" value={mobile} onChange={e=>setMobile(e.target.value)} placeholder={t("mobile_placeholder",language)} inputMode="tel"/><button className="primaryBtn full" onClick={requestOtp} disabled={loading||mobile.length<8}>{loading?t("sending",language):t("send_otp",language)}</button></>:<><input className="textInput" value={otp} onChange={e=>setOtp(e.target.value)} placeholder={t("otp_placeholder",language)} inputMode="numeric"/>{otpHint&&<div className="notice">Hackathon demo OTP: <b>{otpHint}</b></div>}<button className="primaryBtn full" onClick={verifyOtp} disabled={loading||otp.length!==6}>{loading?t("verifying",language):t("verify_continue",language)}</button></>}</main>}
 {page==="intake"&&<main className="intake"><p className="eyebrow">CURRENT HEALTH ISSUE</p><h2>{session?.nextAction?.patient_text||"Please describe what is troubling you today."}</h2><p className="muted">Type, speak, or tap a card — whichever is easiest. Voice transcripts are retained as patient-reported intake turns.</p>{complete?<div className="notice"><b>Your initial history is ready.</b><br/>Finish to save this intake, including voice/text turns, to your patient record and ABHA workspace.</div>:<>{selectingCondition?<div className="grid conditionGrid">{session?.nextAction?.options?.map((o:any)=>{const {value,label}=optionValueLabel(o);return <button key={value} className="card" onClick={()=>send(value,"touch")}><b>{label}</b></button>})}</div>:<div className="options">{session?.nextAction?.options?.map((o:any)=>{const {value,label}=optionValueLabel(o);return <button key={value} onClick={()=>send(value,"touch")}>{label}</button>})}</div>}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder={selectingCondition?t("or_describe_own_words",language):t("intake_placeholder",language)}/>{intakeUpload&&<div className="notice">{intakeUpload.status==="uploading"&&`Uploading ${intakeUpload.filename}…`}{intakeUpload.status==="processing"&&`Running OCR on ${intakeUpload.filename}…`}{intakeUpload.status==="done"&&`📎 ${intakeUpload.filename} — ${intakeUpload.evidenceCount} item(s) extracted. Review and approve them on the Records page.`}</div>}</>}<div className="row"><button className="voice" onClick={speak} disabled={complete||transcribing}>{transcribing?t("transcribing",language):recording?t("stop_recording",language):t("speak",language)}</button><button className="voice" onClick={speakQuestion}>{t("speak_question",language)}</button>{!complete&&<><input ref={intakeFileRef} type="file" accept=".pdf,image/*" hidden onChange={e=>e.target.files?.[0]&&uploadDuringIntake(e.target.files[0])}/><button className="voice" onClick={()=>intakeFileRef.current?.click()} disabled={loading}>{t("upload_instead",language)}</button></>}{complete?<button className="primaryBtn" onClick={completeIssue} disabled={loading||savedIssue}>{loading?t("saving",language):t("finish_save",language)}</button>:<button className="primaryBtn" onClick={()=>send(text)} disabled={loading||!text.trim()}>{loading?t("working",language):t("continue_btn",language)}</button>}</div><p className="safety">{t("safety_line",language)}</p></main>}
 {page==="profile"&&<main className="content"><p className="eyebrow">PROGRESSIVE HEALTH PROFILE</p><h2>My Health</h2><p>Patient-reported profile information remains distinct from sourced clinical evidence.</p><section className="profileGrid">{([["conditions","Known conditions"],["medicines","Current medicines"],["allergies","Allergies"]] as const).map(([key,label])=><label className="profileCard" key={key}><b>{label}</b><span>Patient-reported information</span><textarea value={profile[key]||""} onChange={e=>setProfile({...profile,[key]:e.target.value})} placeholder="Nothing added yet…"/></label>)}</section><button className="primaryBtn" onClick={saveProfile} disabled={loading}>Save to patient record</button><section className="readiness"><h3>Current health issues</h3>{patient?.issues?.length?<div className="evidenceList">{patient.issues.map((i:any)=><div key={i.id}><b>{i.title||"Health issue"}</b><span>{i.summary?.chief_complaint||i.description||"Patient-reported intake"}</span><small>{i.created_at||""}</small></div>)}</div>:<p>No current issues saved yet.</p>}</section><section className="readiness"><h3>Linked medical records</h3>{patient?.records?.length?<div className="evidenceList">{patient.records.map((r:any)=><div key={r.id}><b>{r.title||"Medical record"}</b><span>{r.evidence_count||0} extracted evidence item(s)</span><small>{r.processing_status||"stored"}</small></div>)}</div>:<p>No records linked yet.</p>}</section><div className="notice">✓ This patient context is stored in the shared patient data layer used by PRISM and MedBridge.</div></main>}
 {page==="records"&&<main className="content"><p className="eyebrow">SOURCE-AWARE HEALTH RECORDS</p><h2>Medical Records</h2><p>Upload prescriptions, laboratory reports, discharge summaries and diagnostic documents. OCR output remains linked to the original source.</p><input ref={inputRef} type="file" accept=".pdf,image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><button className="drop" onClick={()=>inputRef.current?.click()} disabled={loading}><b>{loading?"Working on your request…":"Upload a medical document"}</b><small>PDF and image resources · multilingual OCR · provenance-aware extraction</small></button>{recordStatus&&<div className="notice">{recordStatus}</div>}{record&&<RecordCard record={record} confirmedEvidence={confirmedEvidence} rejectedEvidence={rejectedEvidence} onConfirm={confirmEvidence} onReject={rejectEvidence} language={language}/>}<section className="readiness"><h3>Records in this patient workspace</h3><p>{patient?.records?.length||0} record(s) are currently linked to this consented patient context.</p></section></main>}
 {page==="abha"&&<main className="content"><p className="eyebrow">PATIENT-SIDE DIGITAL HEALTH WORKSPACE</p><h2>{patient?.fullName||"My ABHA Health Space"}</h2><p>Your demo Health ID: <b>{patient?.healthId}</b> · Data is organized by origin and can be consumed by PRISM and MedBridge through consented boundaries.</p><section className="dashboardGrid"><div className="profileCard"><b>Current health issues</b><strong>{patient?.issues?.length||0}</strong><span>Captured through PRISM text, touch and voice intake.</span><button onClick={()=>start()}>Add new issue →</button></div><div className="profileCard"><b>Medical records</b><strong>{patient?.records?.length||0}</strong><span>Patient-uploaded sources with OCR provenance.</span><button onClick={()=>setPage("records")}>Manage records →</button></div><div className="profileCard"><b>Health profile</b><strong>{[profile.conditions,profile.medicines,profile.allergies].filter(Boolean).length? "Updated":"Empty"}</strong><span>Conditions, medicines and allergies remain distinct from verified records.</span><button onClick={()=>setPage("profile")}>Update profile →</button></div></section><section className="readiness"><h3>Shared continuity layer</h3><p>SETU demo pool → PRISM intake and MedBridge reconciliation use the same patient identifier and source-aware context. This prototype is not a live national ABHA/ABDM connection.</p><div className="checklist"><div>✓ OTP consent session verified</div><div>✓ Patient-reported data retained separately</div><div>✓ Uploaded record provenance retained</div><div>✓ Voice and text intake retained in the issue context</div><div>✓ MedBridge-ready patient context boundary</div></div></section></main>}
 </div>}
function RecordCard({record,confirmedEvidence,rejectedEvidence,onConfirm,onReject,language}:{record:any;confirmedEvidence:Set<string>;rejectedEvidence:Set<string>;onConfirm:(id:string)=>void;onReject:(id:string)=>void;language:string}){const p=record.processing,ocr=p?.ocr;return <section className="recordCard"><div className="recordHead"><div><b>{record.originalFilename}</b><small>{record.mediaType} · Original source preserved</small></div>{p&&<span className="status">{p.status}</span>}</div>{ocr&&<><div className="metrics"><div><small>OCR ENGINE</small><b>{ocr.engine}</b></div><div><small>PAGES</small><b>{ocr.pages?.length||0}</b></div><div><small>EVIDENCE FOUND</small><b>{p.evidence?.length||0}</b></div></div>{p.evidence?.length>0&&<div className="evidenceList">{p.evidence.filter((e:any)=>!rejectedEvidence.has(e.id)).map((e:any,i:number)=><div key={e.id||i}><b>{e.category||e.kind}</b><span>{e.data?.value??e.value}</span><small>Source page {e.sourcePointers?.[0]?.page||e.page} · {confirmedEvidence.has(e.id)?"patient_confirmed":e.verificationStatus||"source_extracted"}</small>{e.id&&!confirmedEvidence.has(e.id)&&<span className="evidenceActions"><button onClick={()=>onConfirm(e.id)}>{t("looks_right",language)}</button><button onClick={()=>onReject(e.id)}>{t("flag_wrong",language)}</button></span>}</div>)}</div>}<details open><summary>View raw OCR text</summary><pre>{ocr.pages?.map((x:any)=>x.text||"No text returned for this page.").join("\n\n")||"No OCR text returned."}</pre></details></>}</section>}
createRoot(document.getElementById("root")!).render(<App/>);
