import React,{useRef,useState} from "react"; import {createRoot} from "react-dom/client"; import "./styles.css";
type Page="home"|"intake"|"profile"|"records"|"abha"; const API=import.meta.env.VITE_PRISM_API_URL||"http://localhost:8000";
const patientId=localStorage.getItem("prism_patient_id")||crypto.randomUUID();localStorage.setItem("prism_patient_id",patientId);
function App(){const [page,setPage]=useState<Page>("home"),[session,setSession]=useState<any>(null),[text,setText]=useState(""),[loading,setLoading]=useState(false),[language,setLanguage]=useState("en-IN"),[recording,setRecording]=useState(false),[notice,setNotice]=useState("");const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
const start=async()=>{setLoading(true);try{const r=await fetch(API+"/v1/intake/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({patient_id:patientId,language,entry_point:"current_health_issue"})});const s=await r.json();setSession(s);setPage("intake")}catch{setNotice("Unable to start PRISM. Check the API connection.")}finally{setLoading(false)}};
const send=async(value:string,mode="text")=>{if(!session||!value.trim())return;setLoading(true);try{const r=await fetch(API+"/v1/intake/sessions/"+session.id+"/responses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value,input_mode:mode})});setSession(await r.json());setText("")}finally{setLoading(false)}};
const toggleVoice=async()=>{if(!session)return;if(recording){recorder.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=async()=>{setRecording(false);stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"});const fd=new FormData();fd.append("file",blob,"voice.webm");setLoading(true);try{const res=await fetch(API+"/v1/intake/sessions/"+session.id+"/voice",{method:"POST",body:fd});const data=await res.json();if(!res.ok)throw new Error(data.message||"Voice unavailable");setSession(data.session);if(data.transcript)setNotice("Heard: "+data.transcript)}catch(e:any){setNotice(e.message)}finally{setLoading(false)}};r.start();setRecording(true)}catch{setNotice("Microphone permission is required for voice input.")}};
const upload=async(file:File)=>{setLoading(true);setNotice("");try{const fd=new FormData();fd.append("file",file);const r=await fetch(API+"/v1/resources/upload?patient_id="+encodeURIComponent(patientId),{method:"POST",body:fd});const data=await r.json();if(!r.ok)throw new Error(data.error||"Upload failed");setNotice("Record saved. Processing can now extract provenance-aware evidence.");await fetch(API+"/v1/resources/"+data.resource.resourceId+"/process",{method:"POST"})}catch(e:any){setNotice(e.message)}finally{setLoading(false)}};
return <div className="app"><header><button className="brand" onClick={()=>setPage("home")}>PRISM <span>by SETU</span></button><nav>{([["home","Home"],["profile","My Health"],["records","Records"],["abha","ABHA"]] as [Page,string][]).map(([p,label])=><button key={p} onClick={()=>setPage(p)} className={page===p?"active":""}>{label}</button>)}<select value={language} onChange={e=>setLanguage(e.target.value)} aria-label="Language"><option value="en-IN">English</option><option value="ta-IN">தமிழ்</option><option value="hi-IN">हिन्दी</option></select></nav></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
{page==="home"&&<main className="hero"><p className="eyebrow">PATIENT HEALTH WORKSPACE</p><h1>Tell us what you need.<br/>PRISM will meet you there.</h1><p className="sub">Begin guided case-taking, preserve previous records, progressively build your health history, and prepare for consented digital-health connectivity.</p><div className="grid"><button className="card primary" onClick={start} disabled={loading}><b>🩺 I have a health concern</b><span>Describe what is troubling you and begin guided patient case-taking.</span></button><button className="card" onClick={()=>setPage("profile")}><b>❤️ Set up my health profile</b><span>Progressively record allergies, medications and health history.</span></button><button className="card" onClick={()=>setPage("records")}><b>📄 Add previous medical records</b><span>Upload reports and prescriptions with preserved source origin.</span></button><button className="card" onClick={()=>setPage("abha")}><b>🏥 Connect ABHA</b><span>Prepare for consented ABDM health-information exchange.</span></button></div></main>}
{page==="intake"&&<main className="intake"><p className="eyebrow">CURRENT HEALTH ISSUE · {language}</p><h2>{session?.nextAction?.patient_text||session?.next_action?.patient_text||"Please describe what is troubling you today."}</h2><p className="muted">Type, speak, or choose an option. Every mode enters the same PRISM conversation.</p><div className="options">{(session?.nextAction?.options||session?.next_action?.options||[]).map((o:any)=><button key={o.value||o} onClick={()=>send(o.value||o,"touch")}>{o.label||o}</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe in your own words…" /><div className="row"><button className={"voice "+(recording?"recording":"")} onClick={toggleVoice} disabled={loading}>{recording?"● Stop recording":"🎙 Speak"}</button><button className="primaryBtn" onClick={()=>send(text)} disabled={loading}>Continue →</button></div><p className="safety">PRISM collects information for structured clinical intake. It does not diagnose or replace emergency care.</p></main>}
{page==="profile"&&<main className="content"><h2>My Health</h2><p>Profile collection is progressive. You do not need to complete everything before using case-taking.</p><section><h3>Health basics</h3><div className="placeholder">Known conditions · Allergies · Current medications · Past procedures · Family history</div></section></main>}
{page==="records"&&<main className="content"><h2>Medical Records</h2><p>Upload prescriptions, laboratory reports, discharge summaries and diagnostic documents. Original resources remain linked to extracted evidence.</p><label className="drop"><input type="file" accept=".pdf,image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/>Choose a document or drag it here<br/><small>PDF and image resources · source-aware OCR processing</small></label>{loading&&<p className="muted">Working on your request…</p>}</main>}
{page==="abha"&&<main className="content"><h2>ABHA & Digital Health</h2><p>SETU will use the approved ABDM integration path and explicit consent before health-information exchange.</p><div className="placeholder">ABHA-linked information will remain distinguishable from patient-reported and document-extracted information.</div></main>}</div>}
createRoot(document.getElementById("root")!).render(<App/>);