import React,{useState} from "react"; import {createRoot} from "react-dom/client"; import "./styles.css";
type Page="home"|"intake"|"profile"|"records"|"abha";
const API=import.meta.env.VITE_PRISM_API_URL||"http://localhost:8000";
function App(){const [page,setPage]=useState<Page>("home"); const [session,setSession]=useState<any>(null); const [text,setText]=useState(""); const [loading,setLoading]=useState(false);
const start=async()=>{setLoading(true); try{const r=await fetch(API+"/v1/intake/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({language:"en-IN",entry_point:"current_health_issue"})}); const s=await r.json(); setSession(s); setPage("intake")}finally{setLoading(false)}};
const send=async(value:string,mode="text")=>{if(!session||!value.trim())return;setLoading(true);try{const r=await fetch(API+"/v1/intake/sessions/"+session.id+"/responses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value,input_mode:mode})});const next=await r.json();setSession(next);setText("")}finally{setLoading(false)}};
return <div className="app"><header><div className="brand">PRISM <span>by SETU</span></div><nav>{(["home","profile","records","abha"] as Page[]).map(p=><button key={p} onClick={()=>setPage(p)} className={page===p?"active":""}>{p==="home"?"Home":p==="profile"?"My Health":p==="records"?"Records":"ABHA"}</button>)}</nav></header>
{page==="home"&&<main className="hero"><p className="eyebrow">PATIENT HEALTH WORKSPACE</p><h1>Tell us what you need.<br/>PRISM will meet you there.</h1><p className="sub">Start with your current health concern, build your health profile, add previous records, or prepare to connect consented digital health information.</p><div className="grid"><button className="card primary" onClick={start} disabled={loading}><b>🩺 I have a health concern</b><span>Describe what is troubling you and begin guided case-taking.</span></button><button className="card" onClick={()=>setPage("profile")}><b>❤️ Set up my health profile</b><span>Progressively record allergies, medications and health history.</span></button><button className="card" onClick={()=>setPage("records")}><b>📄 Add previous medical records</b><span>Upload reports and prescriptions for provenance-aware processing.</span></button><button className="card" onClick={()=>setPage("abha")}><b>🏥 Connect ABHA</b><span>Prepare for consented ABDM health-information exchange.</span></button></div></main>}
{page==="intake"&&<main className="intake"><p className="eyebrow">CURRENT HEALTH ISSUE</p><h2>{session?.next_action?.patient_text||"Please describe what is troubling you today."}</h2><p className="muted">You can type, speak, or choose an option. PRISM keeps one continuous session.</p><div className="options">{session?.next_action?.options?.map((o:any)=><button key={o.value} onClick={()=>send(o.value,"touch")}>{o.label}</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe in your own words…" /><div className="row"><button className="voice" onClick={()=>alert("Voice capture adapter placeholder. Browser audio will connect to PRISM ASR/Bhashini adapter.")}>🎙 Speak</button><button className="primaryBtn" onClick={()=>send(text)} disabled={loading}>Continue →</button></div><p className="safety">PRISM collects information and supports clinical intake. It does not provide a diagnosis or replace emergency care.</p></main>}
{page==="profile"&&<main className="content"><h2>My Health</h2><p>Profile collection is progressive: you do not need to complete everything before starting case-taking.</p><section><h3>Health basics</h3><div className="placeholder">Known conditions · Allergies · Current medications · Past procedures · Family history</div></section></main>}
{page==="records"&&<main className="content"><h2>Medical Records</h2><p>Upload prescriptions, laboratory reports, discharge summaries and diagnostic documents.</p><div className="drop">Drop a document here or choose a file<br/><small>OCR pipeline will preserve document, page and evidence origin.</small></div></main>}
{page==="abha"&&<main className="content"><h2>ABHA & Digital Health</h2><p>This workspace will connect through the approved ABDM integration path with explicit patient consent.</p><div className="placeholder">Sandbox/adapter integration pending credentials and certified onboarding. ABHA exchange provenance will remain distinct from clinician confirmation.</div></main>}
</div>}
createRoot(document.getElementById("root")!).render(<App/>);