import type {IntakeSession} from "./types.js";
export interface ProtocolQuestion{key:string;text:string;options?:{label:string,value:string}[];required:boolean}
const opts=(...x:string[])=>x.map(value=>({label:value,value}));
const pathways:Record<string,ProtocolQuestion[]>={
 headache:[{key:"onset",text:"When did the headache begin?",required:true},{key:"onset_pattern",text:"Did it start suddenly or gradually?",options:opts("Suddenly","Gradually","Not sure"),required:true},{key:"location",text:"Where do you feel the headache most?",required:true},{key:"severity",text:"How severe is it right now?",options:opts("Mild","Moderate","Severe","Unable to say"),required:true},{key:"associated_symptoms",text:"Have you noticed nausea, fever, vision changes, weakness, or anything else?",required:false}],
 abdominal:[{key:"onset",text:"When did the pain begin?",required:true},{key:"location",text:"Where exactly is the pain located?",required:true},{key:"character",text:"How would you describe the pain?",options:opts("Cramping","Burning","Sharp","Dull","Other"),required:true},{key:"severity",text:"How severe is it right now?",options:opts("Mild","Moderate","Severe"),required:true},{key:"associated_symptoms",text:"Any nausea, vomiting, fever, or bowel changes?",required:false}],
 respiratory:[{key:"onset",text:"When did the breathing problem begin?",required:true},{key:"pattern",text:"Does it happen at rest, during activity, or both?",options:opts("At rest","During activity","Both"),required:true},{key:"severity",text:"How difficult is breathing right now?",options:opts("Mild","Moderate","Severe"),required:true},{key:"associated_symptoms",text:"Any chest discomfort, fever, cough, or wheezing?",required:false}],
 chest:[{key:"onset",text:"When did the discomfort begin?",required:true},{key:"character",text:"How would you describe the feeling?",options:opts("Pressure","Sharp pain","Burning","Tightness","Other"),required:true},{key:"pattern",text:"Is it constant or does it come and go?",options:opts("Constant","Comes and goes"),required:true},{key:"severity",text:"How severe is it right now?",options:opts("Mild","Moderate","Severe"),required:true},{key:"associated_symptoms",text:"Any breathlessness, sweating, nausea, or other symptoms?",required:false}],
 general:[{key:"onset",text:"When did this problem first begin?",required:true},{key:"progression",text:"How has it changed since it began?",required:true},{key:"severity",text:"How severe is it right now?",options:opts("Mild","Moderate","Severe","Unable to say"),required:true},{key:"associated_symptoms",text:"Have you noticed any other symptoms?",required:false}]
};
const background:ProtocolQuestion[]=[{key:"previous_episode",text:"Have you experienced something similar before?",options:opts("Yes","No","Not sure"),required:false},{key:"conditions",text:"Do you have any long-term health conditions relevant to this?",required:false},{key:"medicines",text:"Are you currently taking any regular medicines?",required:false},{key:"allergies",text:"Do you have any known allergies?",required:false}];
export function detectPathway(text:string){const t=text.toLowerCase();if(/headache|head pain|migraine|தலைவலி/.test(t))return"headache";if(/stomach|abdomen|abdominal|belly|வயிற/.test(t))return"abdominal";if(/breath|breathing|shortness|wheez|மூச்ச/.test(t))return"respiratory";if(/chest|மார்ப/.test(t))return"chest";return"general"}
export function questionsFor(session:IntakeSession):ProtocolQuestion[]{const ctx:any=session.clinicalContext;const answered=new Set((ctx.answers||[]).map((a:any)=>a.key));const flow=[...(pathways[ctx.pathway||"general"]||pathways.general),...background];return flow.filter(q=>!answered.has(q.key))}
export function recordAnswer(session:IntakeSession,key:string,value:string,inputMode:string){const ctx:any=session.clinicalContext;ctx.answers=[...(ctx.answers||[]),{key,value,input_mode:inputMode,recorded_at:new Date().toISOString()}];session.clinicalContext=ctx;return session}