import type {IntakeSession} from "../types.js";import {screenRedFlags} from "../safety.js";import {questionsFor,recordAnswer} from "../protocolEngine.js";import {localized,optionObjects} from "./language.js";import type {InputMode,ConversationDecision} from "./types.js";import {RuleConversationModel} from "../intelligence/mockConversationModel.js";
const intelligence=new RuleConversationModel();
function ensureContext(s:IntakeSession){const c:any=s.clinicalContext||{};c.turns=c.turns||[];c.answers=c.answers||[];c.decisionTrace=c.decisionTrace||[];s.clinicalContext=c;return c}
function ask(s:IntakeSession){const next=questionsFor(s)[0];if(!next)return null;return{state:"active",language:s.language,nextAction:{type:"ASK",patient_text:next.text,input_mode:"BOTH" as const,options:optionObjects(next.options)},missing:questionsFor(s).filter(x=>x.required).map(x=>x.key)}}
export function beginConversation(s:IntakeSession):ConversationDecision{ensureContext(s);return{state:"active",language:s.language,nextAction:{type:"ASK",patient_text:localized(s.language,"first","Please tell me, in your own words, what is troubling you today."),input_mode:"BOTH",options:[]},missing:["chief_complaint","onset","progression","severity"]}}
export async function processPatientInput(s:IntakeSession,value:string,inputMode:InputMode):Promise<ConversationDecision>{const ctx=ensureContext(s);const expected:any=ctx.chief_complaint?questionsFor(s)[0]?.key:undefined;const interpretation=await intelligence.interpret({text:value,expectedField:expected,language:s.language,context:ctx});ctx.turns.push({role:"patient",value,inputMode,language:s.language,at:new Date().toISOString()});ctx.decisionTrace.push({at:new Date().toISOString(),stage:"interpret",engine:"conversation_intelligence_v1",intent:interpretation.intent,facts:interpretation.facts.map((f:any)=>f.field)});
if(interpretation.intent==="RECORD_UPLOAD")return{state:s.state,language:s.language,nextAction:{type:"OPEN_RECORD_UPLOAD",patient_text:"You can add your previous medical record now. Your original file will remain linked to extracted information.",input_mode:"NONE",options:[]},missing:questionsFor(s).filter(x=>x.required).map(x=>x.key)};
if(interpretation.intent==="ABHA_CONNECT")return{state:s.state,language:s.language,nextAction:{type:"OPEN_ABHA_CONNECT",patient_text:"ABHA connectivity requires explicit consent and approved ABDM integration.",input_mode:"NONE",options:[]},missing:questionsFor(s).filter(x=>x.required).map(x=>x.key)};
if(!ctx.chief_complaint){ctx.chief_complaint=value;const safety=screenRedFlags(value);ctx.safety_flag=safety;ctx.decisionTrace.push({at:new Date().toISOString(),stage:"chief_complaint",engine:"deterministic_protocol_v1"});if(safety.level==="emergency"){s.state="triage_required";return{state:s.state,language:s.language,safety,nextAction:{type:"TRIAGE_ALERT",patient_text:localized(s.language,"triage","Please seek immediate human medical attention. Do not continue routine intake here."),input_mode:"NONE",options:[]},missing:[]}}}
const current=questionsFor(s)[0];if(current){recordAnswer(s,current.key,value,inputMode);for(const fact of interpretation.facts){if(fact.field!==current.key&&!ctx.answers.some((a:any)=>a.key===fact.field))ctx.answers.push({key:fact.field,value:fact.value,inputMode:"inferred_from_patient_report",confidence:fact.confidence,origin:"patient_reported"})}ctx.decisionTrace.push({at:new Date().toISOString(),stage:"question_answered",engine:"deterministic_protocol_v1",question:current.key});const d=ask(s);if(d)return d}
s.state="history_captured";ctx.decisionTrace.push({at:new Date().toISOString(),stage:"complete",engine:"deterministic_protocol_v1"});return{state:s.state,language:s.language,nextAction:{type:"COMPLETE_SECTION",patient_text:localized(s.language,"complete","Thank you. Your initial history has been captured."),input_mode:"BOTH",options:[]},missing:[]}}