import {randomUUID} from "crypto"; import {findByHealthId,getPatient} from "./patientPoolRepository.js";
type Consent={id:string;doctorId:string;doctorName:string;healthId:string;citizenName:string;otp:string;expiresAt:string;status:"pending"|"verified"|"expired"};
type Session={id:string;consentRequestId:string;doctorId:string;doctorName:string;healthId:string;citizenName:string;startedAt:string;expiresAt:string;status:"active"|"expired"};
const consents=new Map<string,Consent>(); const sessions=new Map<string,Session>();
const DEMO_RECORDS=[
{record_type:"diagnosis",title:"Type 2 Diabetes Mellitus",source_hospital:"AIIMS New Delhi",source_date:"2024-03-15",details:"Established diabetes diagnosis with elevated HbA1c; Metformin continued.",structured_data:{status:"active",hba1c:"8.2%"}},
{record_type:"allergy",title:"Penicillin allergy",source_hospital:"Apollo Hospitals Chennai",source_date:"2023-11-02",details:"Patient-reported rash and breathing difficulty after penicillin exposure.",structured_data:{substance:"penicillin",severity:"high"}},
{record_type:"allergy",title:"No known drug allergies",source_hospital:"AIIMS New Delhi",source_date:"2024-03-16",details:"Discharge summary documents no known drug allergies.",structured_data:{claim:"NKDA"}},
{record_type:"medication",title:"Metformin 500 mg",source_hospital:"AIIMS New Delhi",source_date:"2024-03-16",details:"Twice daily with meals.",structured_data:{dose:"500 mg",frequency:"BD"}},
{record_type:"lab",title:"HbA1c",source_hospital:"Apollo Hospitals Chennai",source_date:"2024-02-21",details:"HbA1c 8.2%, above target.",structured_data:{value:"8.2%",flag:"high"}},
{record_type:"vital",title:"Blood pressure",source_hospital:"Fortis Hospital",source_date:"2024-01-10",details:"138/88 mmHg.",structured_data:{systolic:138,diastolic:88}},
{record_type:"discharge",title:"Routine diabetic assessment",source_hospital:"AIIMS New Delhi",source_date:"2024-03-16",details:"Stable discharge with lifestyle modification advice.",structured_data:{outcome:"stable"}}
];
const doctorId=(name:string,id?:string)=>id||"doc_"+name.toLowerCase().replace(/\s+/g,"_");
const active=(expiresAt:string)=>new Date(expiresAt).getTime()>Date.now();
export async function requestMedBridgeConsent(input:any){const healthId=String(input.health_id||"").trim();const doctorName=String(input.doctor_name||"").trim();if(!healthId||!doctorName)throw new Error("health_id_and_doctor_name_required");const patient=await findByHealthId(healthId);if(!patient)throw new Error("citizen_not_found");const id=randomUUID();const c:Consent={id,doctorId:doctorId(doctorName,input.doctor_id),doctorName,healthId:patient.healthId,citizenName:patient.fullName,otp:"654321",expiresAt:new Date(Date.now()+10*60*1000).toISOString(),status:"pending"};consents.set(id,c);return{consent_request_id:id,citizen_name:c.citizenName,citizen_health_id:c.healthId,otp_expiry:c.expiresAt,demo_otp:c.otp,demo_fallback:true,message:"Demo consent OTP generated. Production delivery must use an approved consent/identity provider."}}
export async function verifyMedBridgeConsent(input:any){const c=consents.get(input.consent_request_id);if(!c)throw new Error("consent_request_not_found");if(c.status!=="pending")throw new Error("consent_not_pending");if(!active(c.expiresAt)){c.status="expired";throw new Error("otp_expired")}if(c.doctorId!==doctorId(String(input.doctor_name||""),input.doctor_id))throw new Error("doctor_mismatch");if(String(input.otp_code)!==c.otp)throw new Error("incorrect_otp");c.status="verified";const s:Session={id:randomUUID(),consentRequestId:c.id,doctorId:c.doctorId,doctorName:c.doctorName,healthId:c.healthId,citizenName:c.citizenName,startedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+30*60*1000).toISOString(),status:"active"};sessions.set(s.id,s);return{session_id:s.id,citizen_id:s.healthId,citizen_name:s.citizenName,started_at:s.startedAt,expires_at:s.expiresAt}}
export async function getMedBridgeContext(sessionId:string){const s=sessions.get(sessionId);if(!s)throw new Error("session_not_found");if(!active(s.expiresAt)){s.status="expired";throw new Error("session_expired")}const p=await findByHealthId(s.healthId);if(!p)throw new Error("patient_not_found");return{session:{session_id:s.id,doctor_name:s.doctorName,expires_at:s.expiresAt},patient:{patient_id:p.patientId,health_id:p.healthId,full_name:p.fullName,profile:p.profile},hospital_records:DEMO_RECORDS.map((r,i)=>({id:"hospital-demo-"+(i+1),...r,source:"hospital_linked_demo"})),patient_issues:p.issues,patient_records:p.records,data_origin:"setu_shared_patient_pool",consent_required:true}}
export async function reconcileMedBridgeSession(sessionId:string){const context=await getMedBridgeContext(sessionId);const records=[...context.hospital_records,...context.patient_records];const allergies=records.filter((r:any)=>String(r.record_type||r.type||"").toLowerCase()==="allergy");const conflicts:any[]=[];if(allergies.some((r:any)=>/no known/i.test(r.title||r.details||""))&&allergies.some((r:any)=>/penicillin/i.test(r.title||r.details||"")))conflicts.push({severity:"high",type:"allergy_conflict",description:"One linked source documents penicillin allergy while another documents no known drug allergies.",recommendation:"Clinician should verify allergy status directly with the patient before prescribing."});return{patient_summary:{full_name:context.patient.full_name,health_id:context.patient.health_id,total_records:records.length,hospital_records:context.hospital_records.length,patient_sided_records:context.patient_records.length,prism_issues:context.patient_issues.length},conflicts,sections:[{type:"hospital_linked",label:"Hospital-linked demo records",records:context.hospital_records},{type:"patient_side",label:"Patient-sided SETU data",records:[...context.patient_issues,...context.patient_records]}],reconciliation_notes:conflicts.length?"Conflict(s) detected; clinician review required.":"No deterministic conflict detected in the currently available records.",ai_mode:"deterministic_demo_reconciliation"}}
export async function getContextByHealthId(healthId:string){const p=await findByHealthId(healthId);if(!p)throw new Error("patient_not_found");return{citizen_id:p.healthId,patient_id:p.patientId,profile:p.profile,current_health_issues:p.issues,patient_uploaded_records:p.records,hospital_records:DEMO_RECORDS,data_origin:"setu_shared_patient_pool",consent_required:true}}