import {randomInt,randomUUID} from "crypto"; import {db,query} from "../db.js"; import {config} from "../config.js";
export type Patient={patientId:string;healthId:string;mobile:string;fullName:string;profile:any;issues:any[];records:any[];createdAt:string;updatedAt:string};
const memory=new Map<string,Patient>(); const tx=new Map<string,{mobile:string;otp:string;expiresAt:number}>(); let ready=false;
async function ensure(){if(!db||ready)return;await query("create table if not exists patient_pool (patient_id uuid primary key, health_id text unique not null, mobile text unique not null, full_name text not null, profile jsonb not null default '{}'::jsonb, issues jsonb not null default '[]'::jsonb, records jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now())");ready=true}
const health=(m:string)=>{const d=m.replace(/\D/g,"").slice(-12).padStart(12,"0");return d.slice(0,2)+"-"+d.slice(2,6)+"-"+d.slice(6,10)+"-"+d.slice(10)};
const normalizeMobile=(m:string)=>{const d=m.replace(/\D/g,""); if(d.length===10)return "+91"+d; return m.startsWith("+")?m:"+"+d};
const mapRow=(r:any):Patient=>({patientId:r.patientId,healthId:r.healthId,mobile:r.mobile,fullName:r.fullName,profile:r.profile||{},issues:r.issues||[],records:r.records||[],createdAt:r.createdAt,updatedAt:r.updatedAt});
const select='select patient_id as "patientId",health_id as "healthId",mobile,full_name as "fullName",profile,issues,records,created_at as "createdAt",updated_at as "updatedAt" from patient_pool';
async function sendTextbeeOtp(mobile:string,otp:string){if(!config.textbeeApiKey)return false; const body:any={recipients:[normalizeMobile(mobile)],message:`SETU verification code: ${otp}. Valid for 5 minutes. Do not share this code.`}; if(config.textbeeDeviceId)body.deviceId=config.textbeeDeviceId; const r=await fetch("https://api.textbee.dev/api/v1/gateway/send-sms",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":config.textbeeApiKey},body:JSON.stringify(body)}); if(!r.ok)throw new Error("sms_delivery_failed"); return true}
export async function requestOtp(mobile:string){const transactionId=randomUUID(),otp=String(randomInt(100000,1000000));tx.set(transactionId,{mobile,otp,expiresAt:Date.now()+5*60*1000});let delivered=false;try{delivered=await sendTextbeeOtp(mobile,otp)}catch(e){tx.delete(transactionId);throw e}return{transaction_id:transactionId,expires_in:300,delivery:delivered?"sms":"demo",...(delivered?{}:{demo_otp:otp}),message:delivered?"Verification code sent by SMS.":"Demo OTP generated. Configure TEXTBEE_API_KEY for live SMS delivery."}}
export async function verifyOtp(transactionId:string,otp:string){const t=tx.get(transactionId);if(!t||t.expiresAt<Date.now()||otp!==t.otp)throw new Error("invalid_or_expired_otp");tx.delete(transactionId);let p=await findByMobile(t.mobile);if(!p)p=await createPatient(t.mobile);return{verified:true,consent_status:"verified",patient:p,access_token:randomUUID(),expires_in:1800}}
export async function findByMobile(mobile:string){await ensure();if(!db){for(const p of memory.values())if(p.mobile===mobile)return p;return null}const rows=await query<any>(select+" where mobile=$1",[mobile]);return rows[0]?mapRow(rows[0]):null}
export async function findByHealthId(healthId:string){await ensure();if(!db){for(const p of memory.values())if(p.healthId===healthId)return p;return null}const rows=await query<any>(select+" where health_id=$1",[healthId]);return rows[0]?mapRow(rows[0]):null}
export async function getPatient(id:string){await ensure();if(!db)return memory.get(id)||null;const rows=await query<any>(select+" where patient_id=$1",[id]);return rows[0]?mapRow(rows[0]):null}
async function createPatient(mobile:string){const patientId=randomUUID();const p:Patient={patientId,healthId:health(mobile),mobile,fullName:"SETU Patient",profile:{conditions:"",medicines:"",allergies:""},issues:[],records:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await ensure();if(!db){memory.set(patientId,p);return p}const rows=await query<any>('insert into patient_pool (patient_id,health_id,mobile,full_name,profile,issues,records) values ($1,$2,$3,$4,$5,$6,$7) returning patient_id as "patientId",health_id as "healthId",mobile,full_name as "fullName",profile,issues,records,created_at as "createdAt",updated_at as "updatedAt"',[p.patientId,p.healthId,p.mobile,p.fullName,p.profile,p.issues,p.records]);return mapRow(rows[0])}
export async function updatePatient(id:string,patch:any){const p=await getPatient(id);if(!p)throw new Error("patient_not_found");const next={...p,...patch,profile:{...p.profile,...(patch.profile||{})},updatedAt:new Date().toISOString()};await ensure();if(!db){memory.set(id,next);return next}const rows=await query<any>('update patient_pool set full_name=$2,profile=$3,issues=$4,records=$5,updated_at=now() where patient_id=$1 returning patient_id as "patientId",health_id as "healthId",mobile,full_name as "fullName",profile,issues,records,created_at as "createdAt",updated_at as "updatedAt"',[id,next.fullName,next.profile,next.issues,next.records]);return mapRow(rows[0])}
export async function addIssue(id:string,issue:any){const p=await getPatient(id);if(!p)throw new Error("patient_not_found");return updatePatient(id,{issues:[...p.issues,{id:randomUUID(),...issue,source:"prism_patient_intake",created_at:new Date().toISOString()}]})}
export async function addRecord(id:string,record:any){const p=await getPatient(id);if(!p)throw new Error("patient_not_found");return updatePatient(id,{records:[...p.records,{id:randomUUID(),...record,source:"patient_uploaded",created_at:new Date().toISOString()}]})}